// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjm9nvOuornM5rgPbftCDFlNINf-PZlOI',
    appId: '1:476594508602:web:c17c55b3259fce33ad3603',
    messagingSenderId: '476594508602',
    projectId: 'healthcare-f5788',
    authDomain: 'healthcare-f5788.firebaseapp.com',
    storageBucket: 'healthcare-f5788.firebasestorage.app',
    measurementId: 'G-01QXK2R5BZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWOqm94N6XZLUf1RO-EjpdWOAUOOGgpSk',
    appId: '1:476594508602:android:8776ebf6b5f2cad9ad3603',
    messagingSenderId: '476594508602',
    projectId: 'healthcare-f5788',
    storageBucket: 'healthcare-f5788.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYPElGyZJD75XwmC1YFVr4PSmTqMoWr68',
    appId: '1:476594508602:ios:6b1e2e830e0cd2f2ad3603',
    messagingSenderId: '476594508602',
    projectId: 'healthcare-f5788',
    storageBucket: 'healthcare-f5788.firebasestorage.app',
    iosBundleId: 'com.example.backendhc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYPElGyZJD75XwmC1YFVr4PSmTqMoWr68',
    appId: '1:476594508602:ios:6b1e2e830e0cd2f2ad3603',
    messagingSenderId: '476594508602',
    projectId: 'healthcare-f5788',
    storageBucket: 'healthcare-f5788.firebasestorage.app',
    iosBundleId: 'com.example.backendhc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjm9nvOuornM5rgPbftCDFlNINf-PZlOI',
    appId: '1:476594508602:web:718f4e86ae8505fcad3603',
    messagingSenderId: '476594508602',
    projectId: 'healthcare-f5788',
    authDomain: 'healthcare-f5788.firebaseapp.com',
    storageBucket: 'healthcare-f5788.firebasestorage.app',
    measurementId: 'G-XE7CSD03Q3',
  );

}